# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20160725_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='operadora',
            field=models.CharField(blank=True, choices=[(1, 'Vivo'), (2, 'Tim')], max_length=2, null=True),
        ),
    ]
